/// Flutter icons CustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
///
import 'package:flutter/cupertino.dart';
import 'package:flutter/widgets.dart';
import 'package:cupertino_icons/cupertino_icons.dart';

class CustomIcons {
  CustomIcons._();

  //Icons with numbers 1-9
  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

/*
  static const IconData five =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData four =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nine =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData one =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seven =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData six =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData three =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData two =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eight =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);*/

  //Icons with shapes (not custom icons but constants from cupertino icons)
  static const IconData triangle = IconData(0xf56f,
      fontFamily: CupertinoIcons.iconFont,
      fontPackage: CupertinoIcons
          .iconFontPackage); //so aufrufen: child: const Icon(CustomIcons.triangle),
  static const IconData circle = IconData(0xf400,
      fontFamily: CupertinoIcons.iconFont,
      fontPackage: CupertinoIcons.iconFontPackage);
  static const IconData square = IconData(0xf7ff,
      fontFamily: CupertinoIcons.iconFont,
      fontPackage: CupertinoIcons.iconFontPackage);
  static const IconData triangle_empty = IconData(0xf87b,
      fontFamily: CupertinoIcons.iconFont,
      fontPackage: CupertinoIcons.iconFontPackage);
  static const IconData circle_empty = IconData(0xf401,
      fontFamily: CupertinoIcons.iconFont,
      fontPackage: CupertinoIcons.iconFontPackage);
  static const IconData square_empty = IconData(0xf7f8,
      fontFamily: CupertinoIcons.iconFont,
      fontPackage: CupertinoIcons.iconFontPackage);

  //Icons with letters A-Z
  static const _kFontFamLetters = 'AlphabetLettersIcons';
  static const String? _kFontPkgLetters = null;

  static const IconData w = IconData(0xe800,
      fontFamily: _kFontFamLetters, fontPackage: _kFontPkgLetters);
  static const IconData v = IconData(0xe801,
      fontFamily: _kFontFamLetters, fontPackage: _kFontPkgLetters);
  static const IconData u = IconData(0xe802,
      fontFamily: _kFontFamLetters, fontPackage: _kFontPkgLetters);
  static const IconData t = IconData(0xe803,
      fontFamily: _kFontFamLetters, fontPackage: _kFontPkgLetters);
  static const IconData s = IconData(0xe804,
      fontFamily: _kFontFamLetters, fontPackage: _kFontPkgLetters);
  static const IconData r = IconData(0xe805,
      fontFamily: _kFontFamLetters, fontPackage: _kFontPkgLetters);
  static const IconData q = IconData(0xe806,
      fontFamily: _kFontFamLetters, fontPackage: _kFontPkgLetters);
  static const IconData p = IconData(0xe807,
      fontFamily: _kFontFamLetters, fontPackage: _kFontPkgLetters);
  static const IconData n = IconData(0xe809,
      fontFamily: _kFontFamLetters, fontPackage: _kFontPkgLetters);
  static const IconData m = IconData(0xe80a,
      fontFamily: _kFontFamLetters, fontPackage: _kFontPkgLetters);
  static const IconData l = IconData(0xe80b,
      fontFamily: _kFontFamLetters, fontPackage: _kFontPkgLetters);
  static const IconData k = IconData(0xe80c,
      fontFamily: _kFontFamLetters, fontPackage: _kFontPkgLetters);
  static const IconData j = IconData(0xe80d,
      fontFamily: _kFontFamLetters, fontPackage: _kFontPkgLetters);
  static const IconData i = IconData(0xe80e,
      fontFamily: _kFontFamLetters, fontPackage: _kFontPkgLetters);
  static const IconData h = IconData(0xe80f,
      fontFamily: _kFontFamLetters, fontPackage: _kFontPkgLetters);
  static const IconData g = IconData(0xe810,
      fontFamily: _kFontFamLetters, fontPackage: _kFontPkgLetters);
  static const IconData f = IconData(0xe811,
      fontFamily: _kFontFamLetters, fontPackage: _kFontPkgLetters);
  static const IconData e = IconData(0xe812,
      fontFamily: _kFontFamLetters, fontPackage: _kFontPkgLetters);
  static const IconData d = IconData(0xe813,
      fontFamily: _kFontFamLetters, fontPackage: _kFontPkgLetters);
  static const IconData c = IconData(0xe814,
      fontFamily: _kFontFamLetters, fontPackage: _kFontPkgLetters);
  static const IconData b = IconData(0xe815,
      fontFamily: _kFontFamLetters, fontPackage: _kFontPkgLetters);
  static const IconData a = IconData(0xe816,
      fontFamily: _kFontFamLetters, fontPackage: _kFontPkgLetters);
  static const IconData z = IconData(0xe817,
      fontFamily: _kFontFamLetters, fontPackage: _kFontPkgLetters);
  static const IconData y = IconData(0xe818,
      fontFamily: _kFontFamLetters, fontPackage: _kFontPkgLetters);
  static const IconData x = IconData(0xe819,
      fontFamily: _kFontFamLetters, fontPackage: _kFontPkgLetters);
  static const IconData o = IconData(0xe81d,
      fontFamily: _kFontFamLetters, fontPackage: _kFontPkgLetters);
}
